spring:
  application:
    name: movies-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/moviesdb
  main:
    allow-circular-references: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/company-services
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: movies-app
      principal-attribute: preferred_username

keycloak:
  auth-server-url: http://localhost:8080
  realm: company-services
  resource: movies-app
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: true

keycloak-ext:
  redirect-url: http://localhost:3000/*

app:
  cors:
    allowed-origins: http://localhost:3000

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

logging:
  level:
    org.springframework.security: DEBUG